/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeanboy_demo_jnitest_NdkTest */

#ifndef _Included_com_jeanboy_demo_jnitest_NdkTest
#define _Included_com_jeanboy_demo_jnitest_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jeanboy_demo_jnitest_NdkTest_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    doAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jeanboy_demo_jnitest_NdkTest_doAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
